### ISSUE TITLE
Defer transaction heartbeat to the time when the first SELECT or DML is executed

### ISSUE THREAD

**Issue by yfuruyama** [cloudspannerecosystem/spanner-cli#100]
We run the [transaction heartbeat](https://github.com/cloudspannerecosystem/spanner-cli/blob/master/session.go#L192-L197) just after a user run `BEGIN;` in the interactive shell, but we can defer starting the heartbeat to the time when the first SELECT or DML is executed.

This is possible because Cloud Spanner allows users to call `BeginTransaction` RPC beforehand so that we can remove overhead of calling `BeginTransaction` when users want to run an actual transaction (e.g. See [WriteSessions](https://github.com/googleapis/google-cloud-go/blob/spanner/v1.12.0/spanner/session.go#L417-L421) in Go).

It's important to start the heartbeat after a user runs a SELECT or DML because the heartbeat uses `SELECT 1` query and it could be recognized as an "older transaction" during deadlock detection ([document](https://cloud.google.com/spanner/docs/transactions#deadlock_detection)).

**Comment by yfuruyama** [comment]
cc: @apstndb

**Comment by apstndb** [comment]
I am wondering which is better deferring only transaction heartbeat or deferring `NewReadWriteStmtBasedTransaction` until the first SELECT or DML is executed.

I have confirmed the read-write transaction doesn't be aborted 10 seconds after `BeginTransaction` without any operations  but it seems no documented guarantee.
If it can be aborted, deferring `NewReadWriteStmtBasedTransaction` may be better about error handling.

**Comment by apstndb** [comment]
Anyway, deferring heartbeat is until SELECT or DML is intuitive.

**Comment by yfuruyama** [comment]
Thanks! Yes deferring `BeginTransaction` call is another idea, but it could introduce another controversial issue (e.g. what should we do when user executes `COMMIT;` or `ROLLBACK;` just after `BEGIN;`? etc).

> I have confirmed the read-write transaction doesn't be aborted 10 seconds after BeginTransaction without any operations but it seems no documented guarantee.

I looked backed on the [document](https://cloud.google.com/spanner/docs/reference/rest/v1/TransactionOptions#idle-transactions) about idle transactions and actually it doesn't mention about when "10 seconds timer" becomes active. However several client libraries depend on this behavior for transaction preparation, so I think we can also depend on this as well.

**Comment by apstndb** [comment]
Ok, it seems rare case that unused-prepared read-write transaction is aborted.
It would be the case of the enclosing session is deleted by server side.

I will not worry for the time being.
