### ISSUE TITLE
Installation issue

### ISSUE THREAD

**Issue by hmxxyy** [cloudspannerecosystem/spanner-cli#114]
Need some help on installation. Thanks!

Got the following installation error while trying to install it on a CentOS linux box, looks like some go lib can't be found, here are the full console log

go get -u github.com/cloudspannerecosystem/spanner-cli
go: downloading github.com/cloudspannerecosystem/spanner-cli v0.9.6
go: downloading cloud.google.com/go v0.79.0
go: downloading github.com/chzyer/readline v0.0.0-20180603132655-2972be24d48e
go: downloading github.com/jessevdk/go-flags v1.4.0
go: downloading github.com/olekukonko/tablewriter v0.0.4
go: downloading github.com/xlab/treeprint v1.0.1-0.20200715141336-10e0bc383e01
go: downloading google.golang.org/api v0.43.0
go: downloading google.golang.org/genproto v0.0.0-20210331142528-b7513248f0ba
go: downloading cloud.google.com/go/spanner v1.17.0
go: downloading google.golang.org/grpc v1.36.1
go: downloading github.com/olekukonko/tablewriter v0.0.5
go: downloading github.com/jessevdk/go-flags v1.5.0
go: downloading github.com/xlab/treeprint v1.1.0
go: downloading google.golang.org/protobuf v1.26.0
go: downloading golang.org/x/sys v0.0.0-20210320140829-1e4c9ba3b0c4
go: downloading github.com/mattn/go-runewidth v0.0.8
go: downloading cloud.google.com/go v0.81.0
go: downloading google.golang.org/grpc v1.37.0
go: downloading github.com/mattn/go-runewidth v0.0.12
go: downloading golang.org/x/sys v0.0.0-20210423185535-09eb48e85fd7
go: downloading google.golang.org/genproto v0.0.0-20210423144448-3a41ef94ed2b
go: downloading github.com/golang/protobuf v1.5.1
go: downloading github.com/googleapis/gax-go/v2 v2.0.5
go: downloading github.com/googleapis/gax-go v1.0.3
go: downloading go.opencensus.io v0.23.0
go: downloading github.com/golang/protobuf v1.5.2
go: downloading golang.org/x/xerrors v0.0.0-20200804184101-5ec99f83aff1
go: downloading golang.org/x/net v0.0.0-20210316092652-d523dce5a7f4
go: downloading github.com/jstemmer/go-junit-report v0.9.1
go: downloading golang.org/x/lint v0.0.0-20201208152925-83fdc39ff7b5
go: downloading golang.org/x/tools v0.1.0
go: downloading golang.org/x/net v0.0.0-20210423184538-5f58ad60dda6
go: downloading github.com/golang/groupcache v0.0.0-20200121045136-8c9f03a8e57e
go: downloading github.com/golang/groupcache v0.0.0-20210331224755-41bb18bfe9da
go: downloading golang.org/x/text v0.3.5
go: downloading golang.org/x/mod v0.4.1
go: downloading golang.org/x/mod v0.4.2
go: downloading golang.org/x/text v0.3.6
go get: google.golang.org/genproto@v0.0.0-20210423144448-3a41ef94ed2b: reading https://proxy.golang.org/google.golang.org/genproto/@v/v0.0.0-20210423144448-3a41ef94ed2b.zip: 403 Forbidden
go get: google.golang.org/genproto@v0.0.0-20210423144448-3a41ef94ed2b: reading https://proxy.golang.org/google.golang.org/genproto/@v/v0.0.0-20210423144448-3a41ef94ed2b.zip: 403 Forbidden
go get: google.golang.org/genproto@v0.0.0-20210423144448-3a41ef94ed2b: reading https://proxy.golang.org/google.golang.org/genproto/@v/v0.0.0-20210423144448-3a41ef94ed2b.zip: 403 Forbidden
go get: google.golang.org/genproto@v0.0.0-20210423144448-3a41ef94ed2b: reading https://proxy.golang.org/google.golang.org/genproto/@v/v0.0.0-20210423144448-3a41ef94ed2b.zip: 403 Forbidden
go get: google.golang.org/genproto@v0.0.0-20210423144448-3a41ef94ed2b: reading https://proxy.golang.org/google.golang.org/genproto/@v/v0.0.0-20210423144448-3a41ef94ed2b.zip: 403 Forbidden
go get: google.golang.org/genproto@v0.0.0-20210423144448-3a41ef94ed2b: reading https://proxy.golang.org/google.golang.org/genproto/@v/v0.0.0-20210423144448-3a41ef94ed2b.zip: 403 Forbidden
go get: google.golang.org/genproto@v0.0.0-20210423144448-3a41ef94ed2b: reading https://proxy.golang.org/google.golang.org/genproto/@v/v0.0.0-20210423144448-3a41ef94ed2b.zip: 403 Forbidden
go get: google.golang.org/genproto@v0.0.0-20210423144448-3a41ef94ed2b: reading https://proxy.golang.org/google.golang.org/genproto/@v/v0.0.0-20210423144448-3a41ef94ed2b.zip: 403 Forbidden
go get: google.golang.org/genproto@v0.0.0-20210423144448-3a41ef94ed2b: reading https://proxy.golang.org/google.golang.org/genproto/@v/v0.0.0-20210423144448-3a41ef94ed2b.zip: 403 Forbidden

**Comment by hmxxyy** [comment]
Go lang version: 
$ go version
go version go1.16.3 linux/amd64

OS version:
cat /etc/redhat-release
CentOS Linux release 7.5.1804 (Core)

**Comment by hmxxyy** [comment]
looks like it pulls a daily snapshot version of google.golang.org/genproto v0.0.0-20210423144448-3a41ef94ed2b.zip which is not there

**Comment by yfuruyama** [comment]
Could you try installing spanner-cli again? Now it looks like `google.golang.org/genproto` has version `v0.0.0-20210423144448-3a41ef94ed2b` in the [list](https://pkg.go.dev/google.golang.org/genproto?tab=versions).

I tried installing now and it successfully finished as follows:

```
$ cat /etc/redhat-release
CentOS Linux release 7.9.2009 (Core)
$ go version
go version go1.16.3 linux/amd64
$ go get -u github.com/cloudspannerecosystem/spanner-cli
go: downloading github.com/cloudspannerecosystem/spanner-cli v0.9.6
go: downloading cloud.google.com/go v0.79.0
go: downloading cloud.google.com/go/spanner v1.17.0
go: downloading cloud.google.com/go v0.81.0
go: downloading github.com/chzyer/readline v0.0.0-20180603132655-2972be24d48e
go: downloading github.com/jessevdk/go-flags v1.4.0
go: downloading github.com/jessevdk/go-flags v1.5.0
go: downloading github.com/olekukonko/tablewriter v0.0.4
go: downloading github.com/olekukonko/tablewriter v0.0.5
go: downloading github.com/xlab/treeprint v1.0.1-0.20200715141336-10e0bc383e01
go: downloading github.com/xlab/treeprint v1.1.0
go: downloading google.golang.org/api v0.43.0
go: downloading google.golang.org/api v0.45.0
go: downloading google.golang.org/genproto v0.0.0-20210331142528-b7513248f0ba
go: downloading google.golang.org/genproto v0.0.0-20210423144448-3a41ef94ed2b
go: downloading google.golang.org/grpc v1.36.1
go: downloading google.golang.org/grpc v1.37.0
go: downloading google.golang.org/protobuf v1.26.0
go: downloading github.com/golang/protobuf v1.5.1
go: downloading github.com/golang/protobuf v1.5.2
go: downloading github.com/googleapis/gax-go/v2 v2.0.5
go: downloading github.com/googleapis/gax-go v1.0.3
go: downloading go.opencensus.io v0.23.0
go: downloading golang.org/x/xerrors v0.0.0-20200804184101-5ec99f83aff1
go: downloading golang.org/x/sys v0.0.0-20210320140829-1e4c9ba3b0c4
go: downloading golang.org/x/sys v0.0.0-20210423185535-09eb48e85fd7
go: downloading github.com/mattn/go-runewidth v0.0.8
go: downloading github.com/mattn/go-runewidth v0.0.12
go: downloading golang.org/x/oauth2 v0.0.0-20210313182246-cd4f82c27b84
go: downloading golang.org/x/oauth2 v0.0.0-20210413134643-5e61552d6c78
go: downloading github.com/jstemmer/go-junit-report v0.9.1
go: downloading golang.org/x/lint v0.0.0-20201208152925-83fdc39ff7b5
go: downloading golang.org/x/tools v0.1.0
go: downloading github.com/golang/groupcache v0.0.0-20200121045136-8c9f03a8e57e
go: downloading github.com/golang/groupcache v0.0.0-20210331224755-41bb18bfe9da
go: downloading google.golang.org/appengine v1.6.7
go: downloading golang.org/x/net v0.0.0-20210316092652-d523dce5a7f4
go: downloading golang.org/x/net v0.0.0-20210423184538-5f58ad60dda6
go: downloading github.com/google/go-cmp v0.5.5
go: downloading golang.org/x/mod v0.4.1
go: downloading golang.org/x/mod v0.4.2
go: downloading golang.org/x/text v0.3.5
go: downloading golang.org/x/text v0.3.6
go: downloading github.com/rivo/uniseg v0.1.0
go: downloading github.com/rivo/uniseg v0.2.0
$ ~/go/bin/spanner-cli -h
Usage:
  spanner-cli [OPTIONS]

spanner:
  -p, --project=    (required) GCP Project ID. [$SPANNER_PROJECT_ID]
  -i, --instance=   (required) Cloud Spanner Instance ID [$SPANNER_INSTANCE_ID]
  -d, --database=   (required) Cloud Spanner Database ID. [$SPANNER_DATABASE_ID]
  -e, --execute=    Execute SQL statement and quit.
  -f, --file=       Execute SQL statement from file and quit.
  -t, --table       Display output in table format for batch mode.
  -v, --verbose     Display verbose output.
      --credential= Use the specific credential file
      --prompt=     Set the prompt to the specified format
      --priority=   Set default request priority (HIGH|MEDIUM|LOW)

Help Options:
  -h, --help        Show this help message

Invalid options```

**Comment by hmxxyy** [comment]
thanks for the quick reply.

Tried a couple of times, still getting the same error, even after removed ~/go directory completely
go: downloading golang.org/x/text v0.3.6
go get: google.golang.org/genproto@v0.0.0-20210423144448-3a41ef94ed2b: reading https://proxy.golang.org/google.golang.org/genproto/@v/v0.0.0-20210423144448-3a41ef94ed2b.zip: 403 Forbidden
go get: google.golang.org/genproto@v0.0.0-20210423144448-3a41ef94ed2b: reading https://proxy.golang.org/google.golang.org/genproto/@v/v0.0.0-20210423144448-3a41ef94ed2b.zip: 403 Forbidden
go get: google.golang.org/genproto@v0.0.0-20210423144448-3a41ef94ed2b: reading https://proxy.golang.org/google.golang.org/genproto/@v/v0.0.0-20210423144448-3a41ef94ed2b.zip: 403 Forbidden
go get: google.golang.org/genproto@v0.0.0-20210423144448-3a41ef94ed2b: reading https://proxy.golang.org/google.golang.org/genproto/@v/v0.0.0-20210423144448-3a41ef94ed2b.zip: 403 Forbidden
go get: google.golang.org/genproto@v0.0.0-20210423144448-3a41ef94ed2b: reading https://proxy.golang.org/google.golang.org/genproto/@v/v0.0.0-20210423144448-3a41ef94ed2b.zip: 403 Forbidden
go get: google.golang.org/genproto@v0.0.0-20210423144448-3a41ef94ed2b: reading https://proxy.golang.org/google.golang.org/genproto/@v/v0.0.0-20210423144448-3a41ef94ed2b.zip: 403 Forbidden
go get: google.golang.org/genproto@v0.0.0-20210423144448-3a41ef94ed2b: reading https://proxy.golang.org/google.golang.org/genproto/@v/v0.0.0-20210423144448-3a41ef94ed2b.zip: 403 Forbidden
go get: google.golang.org/genproto@v0.0.0-20210423144448-3a41ef94ed2b: reading https://proxy.golang.org/google.golang.org/genproto/@v/v0.0.0-20210423144448-3a41ef94ed2b.zip: 403 Forbidden
go get: google.golang.org/genproto@v0.0.0-20210423144448-3a41ef94ed2b: reading https://proxy.golang.org/google.golang.org/genproto/@v/v0.0.0-20210423144448-3a41ef94ed2b.zip: 403 Forbidden

with single command:
$ go get google.golang.org/genproto@v0.0.0-20210423144448-3a41ef94ed2b
go: downloading google.golang.org/genproto v0.0.0-20210423144448-3a41ef94ed2b
go get: google.golang.org/genproto@v0.0.0-20210423144448-3a41ef94ed2b: reading https://proxy.golang.org/google.golang.org/genproto/@v/v0.0.0-20210423144448-3a41ef94ed2b.zip: 403 Forbidden

without version #
go get google.golang.org/genproto
go: downloading google.golang.org/genproto v0.0.0-20210423144448-3a41ef94ed2b
go get: google.golang.org/genproto@v0.0.0-20210423144448-3a41ef94ed2b: reading https://proxy.golang.org/google.golang.org/genproto/@v/v0.0.0-20210423144448-3a41ef94ed2b.zip: 403 Forbidden

might be the proxy has some caching issue? I will retry tomorrow to see how it goes

**Comment by yfuruyama** [comment]
hmm... the weird thing to me is that it got 403 Forbidden.

Could you try `curl -LO https://proxy.golang.org/google.golang.org/genproto/@v/v0.0.0-20210423144448-3a41ef94ed2b.zip` to check if you can download the package itself?

Here is my result. I could download successfully from my laptop.
```
$ curl -LO https://proxy.golang.org/google.golang.org/genproto/@v/v0.0.0-20210423144448-3a41ef94ed2b.zip
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100 10.0M  100 10.0M    0     0  3515k      0  0:00:02  0:00:02 --:--:-- 4470k
```

**Comment by hmxxyy** [comment]
@yfuruyama I think it is the security policy on our firewall caused this. It fails with curl/wget command as well.

I'll close the issue. Thanks so much for your support. Have a wonderful day in Tokyo.

ありがとうございました！
