### ISSUE TITLE
Version Retention

### ISSUE THREAD

**Issue by GCP-ally** [cloudspannerecosystem/spanner-cli#115]
I'm unable to import from a spanner-dump file. Spanner-cli throws and error when it tries to run the first block
``
ALTER DATABASE `example-db` SET OPTIONS (
  version_retention_period = '7d'
);
);
  id STRING(1024),
) PRIMARY KEY(id);
``

**Comment by yfuruyama** [comment]
Thank you for reporting the issue.

[ALTER DATABASE](https://cloud.google.com/spanner/docs/data-definition-language#alter-database) is not supported yet in spanner-cli, so that would be the reason it causes an error.

Let me fix spanner-cli to support ALTER DATABASE clause.
