### ISSUE TITLE
Where's the binary?

### ISSUE THREAD

**Issue by lumberj** [cloudspannerecosystem/spanner-cli#122]
https://github.com/cloudspannerecosystem/spanner-cli/blob/043d3b67688009327300f7e57bc3e6adc313c034/README.md

**Comment by yfuruyama** [comment]
It's a little bit old, but you can install the binary from [here](https://github.com/cloudspannerecosystem/spanner-cli/releases/tag/v0.7.0).

If you want to use the latest one, please install it with `go get` [command](https://github.com/cloudspannerecosystem/spanner-cli#install)
