### ISSUE TITLE
Support Change Streams DDL

### ISSUE THREAD

**Issue by apstndb** [cloudspannerecosystem/spanner-cli#135]
Support DDLs for managing change streams.

https://cloud.google.com/spanner/docs/change-streams/manage?hl=en

* `CREATE CHANGE STREAM <name> FOR ...`
* `ALTER CHANGE STREAM <name> SET FOR ...`
* `ALTER CHANGE STREAM <name> SET OPTIONS ...`
* `ALTER CHANGE STREAM <name> DROP FOR ALL`
* `DROP CHANGE STREAM <name>`

```
spanner> CREATE CHANGE STREAM EverythingStream FOR ALL;
ERROR: invalid statement
```

I propose to support generic `CREATE / DROP / ALTER` DDL statements so that spanner-cli can respond to the new features of Cloud Spanner with a minimum of effort.

**Comment by yfuruyama** [comment]
Sounds good 👍 

We can also think about providing List Change Streams with the syntax like `SHOW CHANGE STREAMS`, but it can be discussed later once we support the above essential DDL.
