### ISSUE TITLE
Proposal: support accessing database with fine-grained access control

### ISSUE THREAD

**Issue by toga4** [cloudspannerecosystem/spanner-cli#146]
CLI Option:
```
spanner-cli -p <project> -i <instance> -d <database> --role <role>
```

Syntax:
```
USE <database> WITH ROLE <role>;
```

https://cloud.google.com/spanner/docs/access-with-fgac?hl=en

**Comment by toga4** [comment]
Prototype implementation: https://github.com/cloudspannerecosystem/spanner-cli/compare/master...toga4:spanner-cli:feature/with-role

**Comment by yfuruyama** [comment]
@toga4 Thank you for your proposal. It's a good idea to support fine-grained access control in spanner-cli.

One suggestion: for `USE` statement, shall we omit `WITH` word? i.e. `USE <database> [ROLE <role>];`

Then it will be consistent with other multi-optional statement, like `BEGIN [RW] [PRIORITY {HIGH|MEDIUM|LOW}] [TAG <tag>];`: https://github.com/cloudspannerecosystem/spanner-cli#syntax

**Comment by toga4** [comment]
@yfuruyama Sure, let's omit it. Then, syntax will be below.

```
USE <database> ROLE <role>;
```

Can I submit a PR with this?

**Comment by yfuruyama** [comment]
Sure, thank you!

FYI: @apstndb @takabow
