### ISSUE TITLE
DmlStatement should show result set of THEN RETURN

### ISSUE THREAD

**Issue by apstndb** [cloudspannerecosystem/spanner-cli#151]
Currently, spanner-cli doesn't show result sets of `DmlStatement`.
[`UPDATE`](https://cloud.google.com/spanner/docs/reference/standard-sql/dml-syntax?hl=en#then_return_3), [`INSERT`](https://cloud.google.com/spanner/docs/reference/standard-sql/dml-syntax?hl=en#insert-and-then-return), and [`DELETE`](https://cloud.google.com/spanner/docs/reference/standard-sql/dml-syntax?hl=en#then_return_2) with a `THEN RETURN` clause return result sets so it is better to support.

We can't use `rwTxn.Update*` and need to use `rwTxn.Query*`.
https://cloud.google.com/spanner/docs/dml-tasks?hl=en#client-library-dml-return

**Comment by yfuruyama** [comment]
cc: @takabow
