### ISSUE TITLE
executing statement followed by comment fails, which seems a bug

### ISSUE THREAD

**Issue by Jumpaku** [cloudspannerecosystem/spanner-cli#153]
Maybe, I found a regression related to processing a comment after a statement.

When the version is v0.9.16, the following command outputs `1`.

```
echo 'select 1; /* comment */' > stmt.sql
spanner-cli -p $PROJECT -i $INSTANCE -d $DATABASE -f stmt.sql
```

However, when the version is v0.9.17 the above command fails with `ERROR: invalid statement`.

Does the behavior with v0.9.17 need correction?

**Comment by yfuruyama** [comment]
Thanks @Jumpaku for the report, and thanks @apstndb for the quick fix.

I have merged the fix and tagged `v0.9.18`: https://github.com/cloudspannerecosystem/spanner-cli/releases/tag/v0.9.18

Thanks!
