### ISSUE TITLE
Support Protocol Buffers

### ISSUE THREAD

**Issue by apstndb** [cloudspannerecosystem/spanner-cli#174]
[Protocol Buffers support](https://cloud.google.com/spanner/docs/reference/standard-sql/protocol-buffers) is already GA.
We can discuss initial support of Protocol Buffers in spanner-cli.

* [ ] DDL support with `CREATE PROTO BUNDLE`
  * Equivalent of ` gcloud spanner databases ddl update DATABASE_NAME --instance=INSTANCE_NAME
  --ddl='CREATE PROTO BUNDLE (`examples.shipping.Order`);' --proto-descriptors-file=order_descriptors.pb`
  * It is hard to define intuitive behavior other than executing a single command with `--execute`.
* [x] Support decoding of proto-related values like `ENUM`s.

**Comment by yfuruyama** [comment]
`CREATE PROTO BUNDLE` statement is tricky because it requires a companion file (proto file) to be sent to the Spanner API altogether.

Then, there might be two possible ways:

1. For interactive mode: Extend `CREATE PROTO BUNDLE` statement in some ways. For example with a comment line, like `CREATE PROTO BUNDLE ... ; # order_descriptors.pb`
2. For batch (command) mode: Create an option similar to `--proto-descriptors-file` of gcloud.

I think the first option is not intuitive. For second option, I don't think users will use that option if the same functionality is available in gcloud.

Overall, my impression is that we can ask users to use gcloud if they want to run `CREATE PROTO BUNDLE` statement.

**Comment by apstndb** [comment]
I agree `CREATE PROTO BUNDLE` support is not intuitive and not useful in current proposal.

What about `PROTO` and `ENUM` types?

### Current behaviour of `PROTO` and `ENUM` typed values.

```
spanner> WITH t AS (SELECT CAST('genre: POP, nationality: "Japan"' AS spanner.examples.music.SingerInfo) AS singer) SELECT t.singer, t.singer.genre, CAST(t.singer AS STRING) AS singer_string, CAST(t.singer.genre AS STRING) AS genre_string FROM t;
+-----------------------------+------------------+---------------------------------+--------------+
| singer                      | genre            | singer_string                   | genre_string |
+-----------------------------+------------------+---------------------------------+--------------+
| string_value:"GgVKYXBhbiAA" | string_value:"0" | nationality: "Japan" genre: POP | POP          |
+-----------------------------+------------------+---------------------------------+--------------+
1 rows in set (1.07 msecs)
```

I think the raw `string_value: ...` is far from ideal output.

### Proposed behavior

There are no message descriptor in ResultSet, so I think it is impossible to print as `_string`.
Most usable information is `ProtoTypeFqn`. spanner-cli can print values as typed values.

```
spanner> WITH t AS (SELECT CAST('genre: POP, nationality: "Japan"' AS spanner.examples.music.SingerInfo) AS singer) SELECT t.singer, t.singer.genre, CAST(t.singer AS STRING) AS singer_string, CAST(t.singer.genre AS STRING) AS genre_string FROM t;
+-----------------------------------------------------+-----------------------------------+---------------------------------+--------------+
| singer                                              | genre                             | singer_string                   | genre_string |
+-----------------------------------------------------+-----------------------------------+---------------------------------+--------------+
| "GgVKYXBhbiAA" AS spanner.examples.music.SingerInfo | 0 AS spanner.examples.music.Genre | nationality: "Japan" genre: POP | POP          |
+-----------------------------------------------------+-----------------------------------+---------------------------------+--------------+
1 rows in set (1.38 msecs)
```

**Comment by apstndb** [comment]
Is this output a little long?

**Comment by yfuruyama** [comment]
> What about PROTO and ENUM types?

Yes, I agree that we should decode PROTO and ENUM typed values properly, but showing the proto field name looks a bit too much.

If users want to check an actual value, they might use `CAST(<column> AS STRING)` as your example shows, so I think just showing the raw value (base64-encoded string for PROTO and string for ENUM) might be adequate in spanner-cli. Spanner Studio (Cloud Console) also shows both types in that style.

**Comment by apstndb** [comment]
I agree FQN type name is too long and the same printing as Spanner Studio is a good choice.
Another option is printing only the last component of the FQN: like `"GgVKYXBhbiAA" AS SingerInfo`, `0 AS Genre`.

**Comment by yfuruyama** [comment]
> Another option is printing only the last component of the FQN: like "GgVKYXBhbiAA" AS SingerInfo, 0 AS Genre.

This is a very edge case, but it could be confusing if a STRING value contains "AS" in the value.

```
spanner> SELECT '"GgVKYXBhbiAA" AS SingerInfo';
+------------------------------+
|                              |
+------------------------------+
| "GgVKYXBhbiAA" AS SingerInfo |
+------------------------------+
1 rows in set (2.13 msecs)
```

So I'm not sure if it's a good idea to annotate the value with a proto type.

**Comment by apstndb** [comment]
I often read databases whose schemas I didn't know, so I was worried about outputting raw values ​​that couldn't be read without knowledge of the schemas.
spanner-cli does not display type information for all values, so let's align it with Spanner Studio for consistency.

**Comment by apstndb** [comment]
I have noticed the `--proto-descriptor-file` is also very useful in interactive mode so I reopen this issue.

I have already implemented the function in my fork.
https://github.com/apstndb/spanner-mycli/#protocol-buffers-support
If you have been interested about this feature, I can contribute.

**Comment by yfuruyama** [comment]
Switching tools between spanner-cli and gcloud just for running protobuf-related statements would be cumbersome, so yeah I'm supportive of adding a command line flag for that.

By the way, what if a user wants to run two `CREATE PROTO BUNDLE` statements with different proto descriptor files? Maybe interactive mode is not so useful for that situation, so they might use a batch mode to run two statements?

**Comment by apstndb** [comment]
> By the way, what if a user wants to run two CREATE PROTO BUNDLE statements with different proto descriptor files? Maybe interactive mode is not so useful for that situation, so they might use a batch mode to run two statements?

I think Cloud Spanner don't permit multiple `CREATE PROTO BUNDLE` unless proto bundle is once dropped by `DROP PROTO BUNDLE`.

I believe it is useful in interactive mode and it is natural to execute another spanner-cli session if users want to use another proto descriptor.
Most frequent usecase is struglling proto types in a single proto descriptor because `ALTER PROTO BUNDLE` lacks `UPSERT`.
`ALTER PROTO BUNDLE INSERT/UPDATE/DELETE` with a single proto descriptor will be a solution of the use cases.

**Comment by apstndb** [comment]
Or we can specify multiple proto descriptor file as like `--proto-descriptors-file=order_descriptors.pb,other_descriptors.pb` and merge them into a single `ProtoDescriptorSet`.

**Comment by yfuruyama** [comment]
> My very frequent usecase is struglling proto types in a single proto descriptor because ALTER PROTO BUNDLE lacks UPSERT.
> Interactive use of ALTER PROTO BUNDLE INSERT/UPDATE/DELETE with a single proto descriptor file will be a solution of the usecase.

Thank you for sharing the use case. It sounds a valid use case for interactive operations.

> (I believe Cloud Spanner doesn't permit multiple CREATE PROTO BUNDLE unless proto bundle is once dropped by DROP PROTO BUNDLE. ALTER PROTO BUNDLE can merge proto descriptors into the schema registry in the database.)

Thank you for pointing it out. But what if a user wants to run a different `CREATE PROTO BUNDLE` statement for different databases? Currently spanner-cli forces a user to specify database by `-d` option when launching the cli, so I think there is some ambiguity if user runs `$ spanner-cli -d db01 --proto-descriptor-file=foo.pb`:

1. Proto descriptor file is only used for `db01` database.
2. Proto descriptor file is used for every database, even if a user switches the database interactively.

I want to refrain from introducing the system variable for now, so I just want to know which one is desirable.

**Comment by apstndb** [comment]
> Thank you for pointing it out. But what if a user wants to run a different `CREATE PROTO BUNDLE` statement for different databases? Currently spanner-cli forces a user to specify database by `-d` option when launching the cli, so I think there is some ambiguity if user runs `$ spanner-cli -d db01 --proto-descriptor-file=foo.pb`:

> 1. Proto descriptor file is only used for db01 database.
> 2. Proto descriptor file is used for every database, even if a user switches the database interactively.

I believe we should choose 2.
It is useful than 1 because it can be possible to use the same proto descriptor for similar databases.

```
$ spanner-cli -d test-db1 --proto-descriptor-file=foo.pb
spanner> CREATE PROTO BUNDLE(ProtoType);
spanner> USE test-db2;
spanner> CREATE PROTO BUNDLE(ProtoType);
```

In another word,
`USE <database>` opens another session, but they are the same invocation of spanner-cli.
`--proto-descriptor-file` should be valid in a single invocation of spanner-cli.

**Comment by yfuruyama** [comment]
Sounds good. Let's stick the provided `--proto-descriptor-file` to the entire spanner-cli session.
