### ISSUE TITLE
DDL batching support

### ISSUE THREAD

**Issue by apstndb** [cloudspannerecosystem/spanner-cli#22]
`spanner-cli -e" {statements} "` can execute multiple statements, but they are executed sequentially.
If statements are DDLs, it should be executed as a single large batch in practice.
https://cloud.google.com/spanner/docs/schema-updates?hl=en#large-updates

Consideration:
* add a flag like `--batch` or not
* check all statements before execution and batch them only if they are all DDL statements
  * or batch a subsequence of statements that are consecutive DDL statements

**Comment by yfuruyama** [comment]
Thank you for filing a feature request.

It makes sense to run multiple DDLs in a batch for better performance, but I'm wondering how many users use `spanner-cli -e "{statements}"` to apply multiple DDLs although they can use `gcloud spanner databases ddl update` for that purpose.

**Comment by apstndb** [comment]
I want to unity the operation between the actual Cloud Spanner instance and an emulator (such as a [handy-spanner](https://github.com/gcpug/handy-spanner)) but `gcloud spanner databases ddl update` doesn't seem to support `SPANNER_EMULATOR_HOST`.
