### ISSUE TITLE
Support more staleness options in `BEGIN RO`

### ISSUE THREAD

**Issue by apstndb** [cloudspannerecosystem/spanner-cli#28]
Currently, `spanner-cli` only utilize staleness options of Strong Read by `BEGIN RO` and Exact Staleness by `BEGIN RO <seconds>`.
If other options Read Timestamp, Max Staleness, Min Read Timestamp is supported, it will be nice for testing purpose.
https://cloud.google.com/spanner/docs/reference/rpc/google.spanner.v1?hl=en#snapshot-read-only-transactions

Additionally, displaying a read timestamp will be useful for some purpose.

**Comment by yfuruyama** [comment]
It sounds good to have more options for staleness read.

What do you think about the following notations for staleness options?

```
# exact staleness (10 sec old)
BEGIN RO 10;

# read timestamp (at 2020-03-30T12:00:00.045123456Z)
BEGIN RO 2020-03-30T12:00:00.045123456Z;

# max staleness (at most 10 sec old)
BEGIN RO BOUNDED 10;

# min read timestamp (at least 2020-03-30T12:00:00.045123456Z)
BEGIN RO BOUNDED 2020-03-30T12:00:00.045123456Z;
```

Also, displaying a read timestamp would be great, but I don't want to show it to all users as most of cases would not use this. Maybe another prompt option fits this use case?

For example, suppose that we define prompt option `\ts` for the timestamp for read transaction,
```
$ spanner-cli --prompt='spanner\t\ts> '
spanner> BEGIN RO BOUNDED 10;
spanner(ro txn)(2020-03-30T12:00:00.045123456Z)> SELECT * FROM t1;
...
```

**Comment by apstndb** [comment]
The both of the notation and the prompt option seems good to me!
`--verbose` option and command like `\set VERBOSITY VERBOSE` can be another choice.

**Comment by yfuruyama** [comment]
Verbose option (`--verbose` or `\set VERBOSITY VERBOSE`) would be great, but let's discuss it in another place since we need to think about what information should be shown with verbose mode.

Okay, then let me implement staleness options with the above notations.

**Comment by yfuruyama** [comment]
@apstndb Sorry, I misunderstand what bounded staleness means.
As this documentation says, we can't use bounded staleness reads for multi-use read-only transactions.
> https://cloud.google.com/spanner/docs/reference/rpc/google.spanner.v1?hl=en#snapshot-read-only-transactions
Because the timestamp negotiation requires up-front knowledge of which rows will be read, it can only be used with single-use read-only transactions.

So I will implement only read timestamp option in this [PR](https://github.com/cloudspannerecosystem/spanner-cli/pull/31).
```
# read timestamp (at 2020-03-30T12:00:00.045123456Z)
BEGIN RO 2020-03-30T12:00:00.045123456Z;
```

**Comment by apstndb** [comment]
I see that max staleness and min read timestamp is only for single use transaction.
Staleness of single use transactions can be implemented using another syntax but it makes `spanner-cli` more complicated.
They will become TODO entry.
