### ISSUE TITLE
Query having `;` in the string literal fails execution in the batch mode

### ISSUE THREAD

**Issue by yfuruyama** [cloudspannerecosystem/spanner-cli#33]
## Issue
If a query has `;` in the string literal, it fails due to the syntax error.
```
$ echo 'select "TL;DR";' | spanner-cli -p ${PROJECT} -i ${INSTANCE} -d ${DATABASE}
ERROR: spanner: code = "InvalidArgument", desc = "Syntax error: Unclosed string literal [at 1:8]\\nselect \\\"TL\\n       ^"
```

This is because spanner-cli simply separates each statement by delimiter `;` or `\G`, so the query was separated in the middle of the statement.
https://github.com/cloudspannerecosystem/spanner-cli/blob/master/cli.go#L323

This only happens for batch execution mode.

## Solutions
1. Parse query and find appropriate delimiters. This is an ideal way, but there is no official Go parser yet ([spansql](https://godoc.org/cloud.google.com/go/spanner/spansql) would have less coverage of supporting queries).
2. (Only for batch execution) Regard a single line as a single query. This looks like a simple solution, but we have to change option `-e` to allow only a single query.

**Comment by yfuruyama** [comment]
@apstndb Do you have any idea or suggestion on this?

**Comment by apstndb** [comment]
I think the full syntax parsing is not needed in this situation.
Like CSV, it would be enough to check whether in-quote or not.

**Comment by yfuruyama** [comment]
Ah that's simple enough. Let's fix with your solution.
