### ISSUE TITLE
Support query-level optimizer version selection

### ISSUE THREAD

**Issue by apstndb** [cloudspannerecosystem/spanner-cli#35]
https://github.com/googleapis/google-cloud-go/blob/master/spanner/CHANGES.md#v130
>Adds the support of providing query options (optimizer version) via three ways (precedence follows the order): client-level < environment variables < query-level. The environment variable is set by "SPANNER_OPTIMIZER_VERSION".

The environment variables based optimizer version will work well but it requires restarting(or another spanner-cli instance).
It would be added by:
* `SET optimizer level`-like configuration statement.
* Option of `EXPLAIN SELECT` statement.

Note:
```
SELECT * FROM SPANNER_SYS.SUPPORTED_OPTIMIZER_VERSIONS
```
seems available.

**Comment by apstndb** [comment]
The optimizer version can be set using `QueryOptions`.
https://pkg.go.dev/cloud.google.com/go/spanner?tab=doc#QueryOptions

**Comment by yfuruyama** [comment]
Now [query optimizer versioning](https://cloud.google.com/spanner/docs/query-optimizer/manage-query-optimizer) has been released and users can use two types of version overrides for spanner-cli.

1) [Environment Variable](https://cloud.google.com/spanner/docs/query-optimizer/manage-query-optimizer#environment-variable)

```
export SPANNER_OPTIMIZER_VERSION="2"
```

2) [Statement hint](https://cloud.google.com/spanner/docs/query-optimizer/manage-query-optimizer#statement-hint)

```
@{OPTIMIZER_VERSION=2} SELECT * FROM MyTable
```

There is no session-level override yet, but I think statement-level override may be suffice for most use cases.

**Comment by apstndb** [comment]
Nice!
I've noticed `EXPLAIN` only support the form `(EXPLAIN|DESCRIBE|DESC) SELECT`,
It should support `WITH` and statement hints.

**Comment by apstndb** [comment]
I will fix `EXPLAIN`.

**Comment by yfuruyama** [comment]
Good catch. Thank you for fixing!

**Comment by yfuruyama** [comment]
Now `EXPLAIN @{OPTIMIZER_VERSION=x}` statement is supported in https://github.com/cloudspannerecosystem/spanner-cli/pull/43, I will close this issue.

Feel free to reopen this, if there is something we have to address for optimizer.
