### ISSUE TITLE
Enhance DDL batching

### ISSUE THREAD

**Issue by apstndb** [cloudspannerecosystem/spanner-cli#38]
Currently, DDL batching is enabled only if all statements are DDL statements.
It can be enhanced to support consecutive DDLs which is followed by another statements.
It is useful to support the use case that database export and import database using DDLs and DMLs in a single file.
e.g. https://github.com/cloudspannerecosystem/spanner-dump

**Comment by yfuruyama** [comment]
Ah, that's a great idea! Can you take on this?

**Comment by apstndb** [comment]
OK, assigned myself.
