### ISSUE TITLE
EXPLAIN <table> is confusing and undocumented

### ISSUE THREAD

**Issue by apstndb** [cloudspannerecosystem/spanner-cli#44]
I have noticed during the work of #43, `EXPLAIN` without `SELECT` is matched with [`showColumnRe`](https://github.com/cloudspannerecosystem/spanner-cli/blob/v0.5.5/statement.go#L69).
```
$ spanner-cli -e 'EXPLAIN WITH t AS (SELECT 1) SELECT * FROM t'
ERROR: table "WITH t AS (SELECT 1) SELECT * FROM t" doesn't exist
```

It is undocumented behavior and confusing result.
IMO, it should be decommissioned or documented.

**Comment by apstndb** [comment]
Some `spanner-cli` statements which is not natively processed by Cloud Spanner are inspired by another SQL DBMS but it seems not well consistent.
https://dev.mysql.com/doc/refman/8.0/en/explain.html
https://www.postgresql.org/docs/current/using-explain.html

**Comment by yfuruyama** [comment]
`EXPLAIN(DESCRIBE) table` is a statement inspired by MySQL.

If you find this is confusing, I'm inclined to delete `EXPLAIN(DESCRIBE) table` as we have an equivalent statement: `SHOW COLUMNS`.

**Comment by apstndb** [comment]
I vote to delete `EXPLAIN <table>` unless it is limited to single identifier and documented.
This makes it hard to identify typo like:
```
EXPLAIN WTIH t AS (SELECT 1) SELECT * FROM t;
EXPLAIN SERECT * FROM t;
EXPLAIN {OPTIMIZER_VERSION=latest} SELECT * FROM t;
```

**Comment by yfuruyama** [comment]
Yeah, that totally makes sense. Let's delete that 👍
