### ISSUE TITLE
Utilize Cloud Spanner Emulator in integration test

### ISSUE THREAD

**Issue by apstndb** [cloudspannerecosystem/spanner-cli#50]
`integration_test.go` can use Cloud Spanner Emulator.
refs https://github.com/googleapis/google-cloud-go/commit/25803d86c6f5d3a315388d369bf6ddecfadfbfb5

**Comment by apstndb** [comment]
I am testing in this branch. `circleci local execute` seems to work well.
``
https://github.com/apstndb/spanner-cli/compare/fix/show-columns-case-sensitiveness...apstndb:feature/use-emulator

**Comment by apstndb** [comment]
It can be coexist with integration test using a real instance.

**Comment by yfuruyama** [comment]
That's a great idea. It enables us to easily run integration test in local.

Can you send a PR?

**Comment by apstndb** [comment]
I think it would be better to test in CircleCI.
<img width="1011" alt="スクリーンショット 2020-05-04 18 22 27" src="https://user-images.githubusercontent.com/803393/80953451-82ad6000-8e36-11ea-989a-e7a9fef83c04.png">

The preferred configuration would be 
* Enable `Build forked pull requests`
  * Because test is not run in forked PR currently.
* Disable `Pass secrets to builds from forked pull requests`
  * Because pass secrets to forked PR can cause security vulnerabilities.

**Comment by yfuruyama** [comment]
Thank you for pointing it out. I didn't realize the forked PR didn't trigger CircleCI build.

Now I enabled "build forked pull requests".
