### ISSUE TITLE
Document precedence of configurations.

### ISSUE THREAD

**Issue by apstndb** [cloudspannerecosystem/spanner-cli#56]
Currently, spanner-cli has various ways of configuration.
- command line options `-p`, `-i`, `-d`
- Environment variables #55 
- `.spanner_cli.cnf` in `$HOME` and current directory #51

Although, precedence is not well documented.
It should be documented to prevent unexpected behaviors.

**Comment by apstndb** [comment]
Currently, `.spanner_cli.cnf` is read from the either of `$HOME` or `$PWD` but reading from the both of them may be more intuitive.

**Comment by yfuruyama** [comment]
What precedence order do you think is natural?

I think natural order would be `command line option` > `environment variable` > `config file`, but current order looks like `command line option` > `config file` > `environment variable`.

**Comment by apstndb** [comment]
I agree with your opinion because config files are expected to be a overridable default.
Current order seems a bit strange.
