### ISSUE TITLE
Support QueryMode=PROFILE a.k.a EXPLAIN ANALYZE

### ISSUE THREAD

**Issue by apstndb** [cloudspannerecosystem/spanner-cli#57]
Currently, `EXPLAIN` statement work as `QueryMode=PLAN`.
I want to see the result of `QueryMode=PROFILE`.

It may be similar to `EXPLAIN ANALYZE` of PostgreSQL.
https://www.postgresql.org/docs/12/sql-explain.html

Considerations:
* What runtime information is displayed?

**Comment by yfuruyama** [comment]
I think we can show same type of information as the Spanner shows in the console.

## Console output
![image](https://user-images.githubusercontent.com/1595215/82801502-5e362800-9eb8-11ea-8c8e-3d5ab8a4dd84.png)

## Example output of spanner-cli

```
spanner> explain analyze select * from Singers@{FORCE_INDEX=SingersByLastName};
+------------------------------------------------------------------------------------------------------+---------------+------------+---------+
| Query_Execution_Plan                                                                                 | Rows_Returned | Executions | Latency |
+------------------------------------------------------------------------------------------------------+---------------+------------+---------+
| .                                                                                                    |               |            |         |
| └── Distributed Union (subquery_cluster_node: 1)                                                     | 2             | 1          | 8.14 ms |
|     └── Distributed Cross Apply (subquery_cluster_node: 11)                                          | 2             | 1          | 8.12 ms |
|         ├── Create Batch                                                                             | -             | -          | -       |
|         │   └── Distributed Union (call_type: Local, subquery_cluster_node: 4)                       | 2             | 1          | 7.93 ms |
|         │       └── Compute Struct                                                                   | 2             | 1          | 7.92 ms |
|         │           └── Scan (Full scan: true, scan_target: SingersByLastName, scan_type: IndexScan) | 2             | 1          | 7.91 ms |
|         └── Serialize Result                                                                         | 2             | 1          | 0.12 ms |
|             └── Cross Apply                                                                          | 2             | 1          | 0.12 ms |
|                 ├── Scan (scan_target: $v2, scan_type: BatchScan)                                    | 2             | 1          | 0 ms    |
|                 └── Distributed Union (call_type: Local, subquery_cluster_node: 17)                  | 2             | 2          | 0.05 ms |
|                     └── FilterScan                                                                   | 2             | 2          | 0.04 ms |
|                         └── Scan (scan_type: TableScan, scan_target: Singers)                        | 2             | 2          | 0.04 ms |
+------------------------------------------------------------------------------------------------------+---------------+------------+---------+
13 rows in set (0.40 sec)
timestamp: 2020-05-25T18:44:03.049295+09:00
cpu:       4.08 msecs
scanned:   4 rows
optimizer: 2
```

## Considerations
- How to show the summary data (cpu time, scanned rows). The above example shows them as if it run with verbose option (`-v`).
- Some `Map` operations has distribution values for the latency. How should we show them properly?

![image](https://user-images.githubusercontent.com/1595215/82801721-bbca7480-9eb8-11ea-8369-2292e3761359.png)

**Comment by apstndb** [comment]
>How to show the summary data (cpu time, scanned rows). The above example shows them as if it run with verbose option (-v).

I expect "EXPLAIN ANALYZE" to emit summary lines but 
there seems to be no strong reason to change the format from `-v`.

>Some Map operations has distribution values for the latency. How should we show them properly?

Let me organize.

The displayed values in the console seems:
|heading| value|
|-|-|
|Rows returned | rows.total|
|Executions | execution_summary.num_executions|
|Latency| latency.mean|

And values in tooltip seems:
|heading| value|
|-|-|
|Total executions| execution_summary.num_executions|
|Mean time per execution| latency.mean|
|Standard deviation| latency.std_deviation|
|Total latency| latency.total|

So five values are needed to cover all information in the console.
Below is just idea(seems long).
```
+------------------------------------------------------------------------------------------------------+---------------+------------+------------------------+
|                                                                                                      |               |            |        Latency         |
|                                                                                                      |               |            +---------+--------------+
| Query_Execution_Plan                                                                                 | Rows_Returned | Executions | Total   | Mean±StdDev  |
+------------------------------------------------------------------------------------------------------+---------------+------------+---------+--------------+
|             └── Cross Apply                                                                          | 2             | 1          | 0.12 ms |              |
|                 ├── Scan (scan_target: $v2, scan_type: BatchScan)                                    | 2             | 1          | 0 ms    |              |
|                 └── Distributed Union (call_type: Local, subquery_cluster_node: 17)                  | 2             | 2          | 0.11 ms | 0.05±0.04 ms |
+------------------------------------------------------------------------------------------------------+---------------+------------+---------+--------------+

```

**Comment by yfuruyama** [comment]
Thank you for summarizing that.

Considering we have `\G` separator, multi-line header would be not natural.

If we show all of items in a single line, it would look like this.
```
+------------------------------------------------------------------------------------------------------+---------------+------------+---------------+---------------------+
| Query_Execution_Plan                                                                                 | Rows_Returned | Executions | Latency_total | Latency_mean_stddev |
+------------------------------------------------------------------------------------------------------+---------------+------------+---------------+---------------------+
|             └── Cross Apply                                                                          | 2             | 1          | 0.12 ms       |                     |
|                 ├── Scan (scan_target: $v2, scan_type: BatchScan)                                    | 2             | 1          | 0 ms          |                     |
|                 └── Distributed Union (call_type: Local, subquery_cluster_node: 17)                  | 2             | 2          | 0.11 ms       | 0.05±0.04 ms        |
+------------------------------------------------------------------------------------------------------+---------------+------------+-------------------------------------+
```

I'm not quite sure how `latency.mean` and `latency.std_deviation` is useful for users to investigate the query.

**Comment by apstndb** [comment]
I am wondering whether supporting `\G` is required in all statements.
Either way, terminal width is limited so displayed column should be minimal.

## Example

IMHO, total latency is intuitive rather than mean latency.(Σ is known as ambiguous width character unfortunately.)

```
+------------------------------------------------------------------------------------------------------+----------+-------+----------+
| Query_Execution_Plan                                                                                 | Returned | Exec. | ΣLatency |
+------------------------------------------------------------------------------------------------------+----------+-------+----------+
|             └── Cross Apply                                                                          |   2 rows | 1     |  0.12 ms |
|                 ├── Scan (scan_target: $v2, scan_type: BatchScan)                                    |   2 rows | 1     |     0 ms |
|                 └── Distributed Union (call_type: Local, subquery_cluster_node: 17)                  |   2 rows | 2     |  0.11 ms |
+------------------------------------------------------------------------------------------------------+----------+-------+----------+
```

It seems no visualizer fits all use case.
I am trying to write external formatter which receive jsonpb representation of ResultSet from `gcloud spanner databases execute-sql --query-mode=PROFILE --format=json` to achieve my own use case.

**Comment by yfuruyama** [comment]
This is trivial thing, but I don't think it's effective to shorten the length of the column names as the most width-dominant column could be `Query_Execution_Plan` in the most cases. Rather than abbreviating some column names, I prefer to choosing accurate, descriptive names.

> IMHO, total latency is intuitive rather than mean latency.

I agree. This is not consistent with console UI, but I believe total latency is more useful to investigate the query.

**Comment by apstndb** [comment]
I have a different opinion.
Wrapped table layout is hard to read and width of terminal is limited in some cases(screenshots, large font in presentation, tiling window).
Because 1 depth needs 4 characters, reducing 12 character allows to display 3 levels deeper plan.

**Comment by apstndb** [comment]
Examples of long width table in markdown, text and image.
https://gist.github.com/apstndb/beea6021d5209a30f25b218c89b9fc32

**Comment by yfuruyama** [comment]
What I wanted to say is that the `Query_Execution_Plan` column still account for the most part of the width and even if we shorten the length of the other columns, I doubt that the entire result can be shown in the limited screen.

So if we want to care about the width of the result, I think we also need to consider if we can do to shorten the `Query_Execution_Plan` column as well. For example, we can wrap long texts with [tablewriter](https://pkg.go.dev/github.com/olekukonko/tablewriter?tab=doc#example-package-Autowrap).

Anyway, let's implement this and see how it looks like.

**Comment by yfuruyama** [comment]
@apstndb Can you take both #57 and #58? I can take either of tasks, so please feel free to ask me.

**Comment by apstndb** [comment]
I agree that we need to consider wrap text to fit terminal width in tablewriter.

There are another idea to reduce `Query_Execution_Plan` value width by composing `metadata`.

* `scan_target: SingersByLastName, scan_type: IndexScan` can be shorten to `Index: SingerByLastName`.
* `call_type` can be composed to node name, e.g.
  * `Distributed Union (call_type: Local)` can be shorten to `Local Distributed Union`
  * `Sort Limit (call_type: Global)` can be shorten to `Global Sort Limit`

This notation is consistent with [Query execution operators
](https://cloud.google.com/spanner/docs/query-execution-operators?hl=en) and [Query execution plans](https://cloud.google.com/spanner/docs/query-execution-plans?hl=en)

> Can you take both #57 and #58? I can take either of tasks, so please feel free to ask me.
#57 is already concrete so I'll do it.

**Comment by yfuruyama** [comment]
> There are another idea to reduce Query_Execution_Plan value width by combining metadata entries.

Yeah sounds goods to me 👍
