### ISSUE TITLE
Improve EXPLAIN (add child type)

### ISSUE THREAD

**Issue by apstndb** [cloudspannerecosystem/spanner-cli#58]
The query plan has a large amount of raw information, so the information displayed is limited.
Some information may be reasonable to display additionally.

## Child Type

Binary operators has [`Type` of `ChildLink`](https://cloud.google.com/spanner/docs/reference/rpc/google.spanner.v1?hl=en#childlink) and they are referred in Official document.
https://cloud.google.com/spanner/docs/query-execution-operators?hl=en#cross-apply

Web UI displays child type like below:
![image](https://user-images.githubusercontent.com/803393/82782358-1b178d00-9e97-11ea-8922-ecc62d95a442.png)

`EXPLAIN` of `spanner-cli` may be enhanced like below:
```
$ spanner-cli -e 'EXPLAIN SELECT * FROM Albums@{FORCE_INDEX=AlbumsByAlbumTitle}'
Query_Execution_Plan (EXPERIMENTAL)

.
└── Distributed Union (subquery_cluster_node: 1)
    └── Distributed Cross Apply (subquery_cluster_node: 13)
        ├── Create Batch 
        │   └── Distributed Union (call_type: Local, subquery_cluster_node: 4)
        │       └── Compute Struct 
        │           └── Scan (scan_type: IndexScan, Full scan: true, scan_target: AlbumsByAlbumTitle)
        └── [Map]  Serialize Result 
            └── Cross Apply 
                ├── Scan (scan_target: $v2, scan_type: BatchScan)
                └── [Map]  Distributed Union (call_type: Local, subquery_cluster_node: 20)
                    └── FilterScan 
                        └── Scan (scan_target: Albums, scan_type: TableScan)

```
(Real `Cross Apply` and `Distributed Cross Apply` seems not to have `Input` type with the first child.)

**Comment by yfuruyama** [comment]
Sounds good. Let's add [ChildLink.type](https://cloud.google.com/spanner/docs/reference/rpc/google.spanner.v1?hl=en#childlink) to make the operands clear.

> (Real Cross Apply and Distributed Cross Apply seems not to have Input type with the first child.)

Did you mean the both operations didn't have the child link which type is `Input`?

**Comment by apstndb** [comment]
Yes, it doesn't have `Input`-typed child. It seems inconsistent with the documentation and the Web UI.

```
    - childLinks:         
      - childIndex: 2         
      - childIndex: 13     
        type: Map
      - childIndex: 36
        type: Split Range 
      displayName: Distributed Cross Apply
```

**Comment by yfuruyama** [comment]
I see. Probably we can assume that 0th value of child_links for (Distributed)Cross|Outer Apply operator has `Input` type and 1th value has `Map` type.

**Comment by apstndb** [comment]
> Probably we can assume that 0th value of child_links for (Distributed)Cross|Outer Apply operator has Input type and 1th value has Map type.

We will do so because denoting `Input` type is useful.
