### ISSUE TITLE
Show predicates like Seek/Residual Conditions

### ISSUE THREAD

**Issue by apstndb** [cloudspannerecosystem/spanner-cli#69]
Currently, `EXPLAIN` and `EXPLAIN ANALYZE` don't show predicate functions like `Seek Condition`, `Residual Condition` and `Split Predicate`.
They are described in [Query execution operators docs](https://cloud.google.com/spanner/docs/query-execution-operators?hl=en) and very useful to optimize queries.

It should be considered how to show predicates.

The display format of the execution plans in other databases may be helpful in designing.
* https://use-the-index-luke.com/sql/explain-plan

**Comment by yfuruyama** [comment]
I'm ex-MySQL user and I like `Extra` column to describe such predicates.

Pros:
* Most of MySQL user would be familiar with `Extra` column and what it means.
* We can show multiple extra information like mysql `Using where; Using join buffer`, or `Using where\nUsing join buffer`.

Cons:
* It takes a width for the column length.

**Comment by apstndb** [comment]
I am considering Oracle-like format.
https://use-the-index-luke.com/sql/explain-plan/oracle/filter-predicates

Pros:
* It does only append only ID columns into the table
  * Less column width overhead
* It seems compatible with complex predicates

Cons:
* It require another display area outside of `tablewrite`

## Example

```
$ spaner-cli -e "EXPLAIN ANALYZE SELECT AlbumId, AlbumTitle FROM Albums@{FORCE_INDEX=AlbumsByAlbumTitle} WHERE REGEXP_CONTAINS(AlbumTitle, '^G.*n')" --table
+----+-----------------------------------------------------------+---------------+------------+---------------+
| ID | Query_Execution_Plan                                      | Rows_Returned | Executions | Total_Latency |
+----+-----------------------------------------------------------+---------------+------------+---------------+
|    | .                                                         |               |            |               |
| 0  | +- Distributed Union                                      | 1             | 1          | 0.38 msecs    |
| 1  |     +- Local Distributed Union                            | 1             | 1          | 0.31 msecs    |
| 2  |         +- Serialize Result                               | 1             | 1          | 0.29 msecs    |
| 3  |             +- FilterScan                                 | 1             | 1          | 0.28 msecs    |
| 4  |                 +- Index Scan (Index: AlbumsByAlbumTitle) | 1             | 1          | 0.28 msecs    |
+----+-----------------------------------------------------------+---------------+------------+---------------+
Predicates(identified by ID):
  0:  Split Range: (STARTS_WITH($AlbumTitle, 'G') AND REGEXP_CONTAINS($AlbumTitle, '^G.*n'))
  3:  Seek Condition: STARTS_WITH($AlbumTitle, 'G')
      Residual Condition: REGEXP_CONTAINS($AlbumTitle, '^G.*n')

1 rows in set (6.32 msecs)
timestamp: 2020-06-16T23:45:02.716964+09:00
cpu:       3.67 msecs
scanned:   2 rows
optimizer: 2
```

**Comment by apstndb** [comment]
IMHO, the format should be compatible with Cloud Spanner predicates rather than another RDBMS.

**Comment by yfuruyama** [comment]
That looks an interesting idea. It can prevent the column width from being wide.

Why don't we implement this style and see how it works for real world queries?

**Comment by apstndb** [comment]
OK, I have implemented prototype. #70 
(It may be time to reconsider the column names of `Rows_Returned` and `Executions`.)

**Comment by yfuruyama** [comment]
Thanks! I will review it in a few days.
