### ISSUE TITLE
Support EXPLAIN of DML

### ISSUE THREAD

**Issue by apstndb** [cloudspannerecosystem/spanner-cli#75]
DML has execution plans and it is useful to see plans of queries which have subqueries.
https://cloud.google.com/spanner/docs/query-execution-operators?hl=en#apply-mutations

Currently, the target of `EXPLAIN` is limited for `WITH`, `SELECT` and statement hints but it can be loosen.
https://github.com/cloudspannerecosystem/spanner-cli/blob/v0.7.5/statement.go#L97

**Comment by yfuruyama** [comment]
I'm not sure if it is really useful to check the execution plan of DMLs, but I don't disagree with loosing the rule.
