### ISSUE TITLE
Stdout affected row count when executed sql from file

### ISSUE THREAD

**Issue by k-yomo** [cloudspannerecosystem/spanner-cli#80]
When update sql is executed with `-f` flag, the result is not shown in stdout.
It would be better to stdout update/delete result as well

**Comment by yfuruyama** [comment]
Thanks for filing a feature request.

That's good point. I think affected rows count can be shown to the user only if they specified the option for verbose output (`-v`). This looks like a consistent behavior with other tools (e.g. [mysql](https://dev.mysql.com/doc/refman/8.0/en/mysql-command-options.html#option_mysql_verbose) shows affected rows in batch mode with `-vvv` option.)

**Comment by yfuruyama** [comment]
@k-yomo Does this sound good for your use case?

**Comment by k-yomo** [comment]
@yfuruyama 
Thank you for the reply.

> I think affected rows count can be shown to the user only if they specified the option for verbose output (-v)

I agree on that behavior, but even though we set -v option, affected row count wasn't shown on stdout.
I'll check if it does work or not.

**Comment by yfuruyama** [comment]
Apologies for confusing you. Thanks for hearing your use case 👍 

I'll implement the option to cover this use case.

**Comment by yfuruyama** [comment]
@k-yomo We've launched this feature at [v0.7.8](https://github.com/cloudspannerecosystem/spanner-cli/releases/tag/v0.7.8). Please try it out.

**Comment by k-yomo** [comment]
@yfuruyama 
Thank you for the very quick implementation.
really appreciate it!!
