### ISSUE TITLE
Finish read-write transaction when aborted

### ISSUE THREAD

**Issue by apstndb** [cloudspannerecosystem/spanner-cli#95]
Currently, spanner-cli continues read-write transaction mode when the RPC returns a code "Aborted".

```
> BEGIN RW;
Query OK, 0 rows affected (0.01 sec)

(rw txn)> @{LOCK_SCANNED_RANGES=exclusive} SELECT * FROM tbl WHERE pk = 0;
Empty set (3.72 msecs)

(rw txn)> @{LOCK_SCANNED_RANGES=exclusive} SELECT * FROM tbl WHERE pk = 0;
ERROR: spanner: code = "Aborted", desc = "Transaction was aborted."
(rw txn)> BEGIN RW;
ERROR: you're in read-write transaction. Please finish the transaction by 'COMMIT;' or 'ROLLBACK;'
(rw txn)> COMMIT;
ERROR: spanner: code = "Aborted", desc = "Transaction was aborted."
> BEGIN RW;
Query OK, 0 rows affected (2.22 sec)
```

In this state, users can't execute another statement until execute `ROLLBACK` or `COMMIT`.
(`^D` terminates spanner-cli)

## Expected behavior

Finish read-write transaction mode when aborted and users can continue another operations immediately.

```
> BEGIN RW;
Query OK, 0 rows affected (0.01 sec)

(rw txn)> @{LOCK_SCANNED_RANGES=exclusive} SELECT * FROM tbl WHERE pk = 0;
Empty set (3.72 msecs)

(rw txn)> @{LOCK_SCANNED_RANGES=exclusive} SELECT * FROM tbl WHERE pk = 0;
ERROR: spanner: code = "Aborted", desc = "Transaction was aborted."
> BEGIN RW;
Query OK, 0 rows affected (2.22 sec)
```

**Comment by yfuruyama** [comment]
That's good catch! I think it's because while the [error](https://github.com/cloudspannerecosystem/spanner-cli/blob/master/statement.go#L756-L761) raised in DML statement is handled, the [error](https://github.com/cloudspannerecosystem/spanner-cli/blob/master/statement.go#L756-L761) raised in SELECT statement is not handled properly.

Could you create a patch for this issue?

**Comment by apstndb** [comment]
OK. I'll fix it.

**Comment by yfuruyama** [comment]
Thanks!
