### ISSUE TITLE
Is there a way to get query result as CSV?

### ISSUE THREAD

**Issue by k-yomo** [cloudspannerecosystem/spanner-cli#97]
It would be great if there is a way to get the query result as CSV to be able to export it to BigQuery or other databases.

**Comment by yfuruyama** [comment]
@k-yomo Thank you for filing a feature request.

I can understand it would be useful to get the result as CSV, but could you elaborate on your use cases?

For exporting to BigQuery, we can use [Cloud Spanner export](https://cloud.google.com/spanner/docs/export) to export database to Cloud Storage in Avro format, and BigQuery can load it.

Also spanner-cli outputs the result in TSV format and we can convert them to CSV with a simple script (e.g. [tsv2csv.go](https://gist.github.com/yfuruyama/1458aad949c5f89f0e3cf5715b579ed1)). This is not a perfect solution as in some cases record contains a tab character (`\t`) and it produces an invalid TSV data, but it would work for most of use cases.

```
$ spanner-cli -p ${PROJECT} -i ${INSTANCE} -d ${DATABASE} -e "SELECT * FROM Singers" | go run tsv2csv.go
SingerId,FirstName,LastName,SingerInfo,BirthDate
1,Marc,Richards,NULL,1970-09-03
2,Catalina,Smith,NULL,1990-08-17
3,Alice,Trentor,NULL,1991-10-02
4,Lea,Martin,NULL,1991-11-09
5,David,Lomond,NULL,1977-01-29
```

**Comment by k-yomo** [comment]
@yfuruyama 
Thank you for the detailed comment with solutions!!
The second one(convert tsv to csv) would work with our use case(exporting filtered records in a table to BigQuery).

**Comment by yfuruyama** [comment]
Happy to hear that. Let us know if there are any other use cases where CSV support would be helpful.
